### ISSUE TITLE
Character Recognition

### ISSUE THREAD

**Issue by jluisfgarza** [JDCTeam/issue_tracking_cm#45] opened 2015-08-23 23:50 UTC
Character Recognition: The system displays a square, instead of accents and other characters. (á é í ó ú ñ, etc.)

**Comment by B--B** [comment] 2015-08-24 16:56
Provide more info as requested and your language, everything works fine on italian language

**Comment by ghost** [comment] 2015-08-24 19:34
Samsung i337m, spanish. The problem is not always, but on certain apps.

**Comment by AntaresOne** [comment] 2015-10-28 21:19
@JuanLuisFG it depends exclusively on the apps, report closed as not ROM's bug.

**Closed as completed by AntaresOne** 2015-10-28 21:19 UTC
